# Generated by Django 5.0.1 on 2024-01-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries_App', '0002_population_country_density_country_fertility_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Not Available', max_length=45)),
                ('gdp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Countries_App.gdp')),
            ],
        ),
    ]
